# General Settings
input_file_path: "HIGGS.csv"
test_size: 0.2
seed: 42
class_labels: ["Background", "Signal"]

# Model Parameters
model_parameters:
  - name: "MLP_21ft"
    epochs: 1
    batch_size: 8192
    learning_rate: 0.001
    early_stop_patience: 5
    lr_plateau_reduction_patience: 5
    validation_size: 0.2
    use_features: "1-21"
    hidden_layers: [1240, 512, 256, 128]
    dropout_layers: [0.3, 0.2, 0.2, 0.2]

  - name: "MLP_28ft"
    epochs: 1
    batch_size: 8192
    learning_rate: 0.001
    early_stop_patience: 5
    lr_plateau_reduction_patience: 5
    validation_size: 0.2
    use_features: "1-28"
    hidden_layers: [1240, 256]
    dropout_layers: [0.3, 0.2]

  - name: "CNN"
    epochs: 1
    batch_size: 8192
    learning_rate: 0.001
    early_stop_patience: 5
    lr_plateau_reduction_patience: 5
    validation_size: 0.2
    use_features: "1-21"
    conv_layers: [[44, 2], [22, 2]]
    conv_pool_size: [2, 0]
    hidden_layers: [512, 256]
    dropout_layers: [0.3, 0.2]